name: Azure Login Test

on:
  workflow_dispatch:

jobs:
  login-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ cf50604d-41fe-4339-8f9e-69279db5840f}}
          tenant-id: ${{ 29e86e0d-dcaa-4009-8df8-cb8d0cc55150 }}
          subscription-id: ${{ 6c058af8-517f-4141-88fb-6caec86dfeee }}
          client-secret: ${{ ef83bfa4-10f6-442a-a8bb-37bb74278bbb }}

      - name: Show Azure Account
        run: az account show